server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: users
    password: users
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
