server:
  port: 8080

scalar:
  enabled: true
  path: /docs        # URL da UI
  url: http://localhost:8080/v3/api-docs

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learnJava
    username: userDbJavaLearn
    password: pass1Db2Java3Learn
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
